# Ruby CircleCI 2.1 configuration file
#
# Check https://circleci.com/docs/2.0/ruby/ for more details
#
version: 2.1

jobs:
  build:
    docker:
      - image: cirrusci/flutter
    steps:
      - checkout
      - run: echo $GCLOUD_KEY > ${HOME}/gcloud-service-key.json
      - run: cat  ${HOME}/gcloud-service-key.json
      - run: flutter doctor
      - run: flutter test
      - run: flutter -v build apk
